config/routes.rb
Rails.application.routes.draw do




  resources :categories

  root to: 'pages#home'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :registrations, only: [:create]
  resources :users, only: [:show]
  resources :events, except: [:destroy]

  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos

  namespace :api do
    resources :events
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true

  has_and_belongs_to_many :categories

  has_many :photos, dependent: :destroy

  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  #validates :starts_at, presence: true#,date: { before:  :starts_at}
  #validates :ends_at, presence: true
  validate :end_date_after_start_date


  def end_date_after_start_date
    if ends_at.present? && starts_at.present? && ends_at <= starts_at
      errors.add :ends_at, "must be after start date"
    end
end

def bargain?
  price < 60
end

def self.order_by_price
    order :price
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
   where("first_name LIKE ?", "#{letter}%").order(:first_name)
 end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_secure_token

  has_many :registrations, dependent: :destroy

  has_many :booked_events, through: :registrations, source: :event
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      redirect_to edit_room_path(@event), notice: "Event created"
    end
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission"
    end
   end

  def update
    if @event.update(event_params)
      image_params.each do |image|
      @event.photos.create(image: image)
    end

    redirect_to edit_event_path(@event), notice: "Event updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
      .require(:event)
      .permit(
        :name, :description, :location, :price, :capacity, :includes_food,
        :includes_drinks, :starts_at, :ends_at, :active, theme_ids: []
      )
  end

  def image_params
    params[:images].present? ?
  params.require(:images) : []
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    @event = @photo.event

    @photo.destroy
    @photos = Photo.where(event_id: @event.id)

    # if @event.user.id == current_user.id
    #   photo.destroy
    #
    #   redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    # else
    #   redirect_to @event, notice: "Cannot delete that photo"

    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    

    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h2 class="text-center well">Welcome to Codaisseurup</h2>

  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">

          <img src="https://sites.google.com/a/usd269.net/rooster-nation/_/rsrc/1448462652962/come-with-us/come-play-with-us/COME%20LEARN%20WITH%20US.jpg" alt="Codaisseurup" style="width:100%">


      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">

          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjLx505qIj8lNg01r5FnMrKvh2u3rK1K8WV77Fb9kFm1xXqapv" alt="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjLx505qIj8lNg01r5FnMrKvh2u3rK1K8WV77Fb9kFm1xXqapv" style="width:100%">


      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">

          <img src="http://under30ceo.com/wp-content/uploads/2013/04/How-to-Host-a-Successful-Meetup-300x187.jpg" alt="Codaisseurup" style="width:100%">

      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false"><%= current_user.has_profile? ? current_user.full_name : current_user.email %> <span class="caret"></span></a>



            <ul class="dropdown-menu">
               <li><%= link_to "Your Events", events_path %></li>

              <!--<li><%= link_to "Edit Profile", edit_user_registration_path %></li>-->
              <li role="separator" class="divider"></li>

               <% if current_user.has_profile? %>
                  <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
               <% else %>
                  <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
                <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>