config/routes.rb
Rails.application.routes.draw do




  resources :categories

  root to: 'pages#home'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :registrations, only: [:create]
  resources :users, only: [:show]
  resources :events, except: [:destroy]

  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos

  namespace :api do
    resources :events
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true

  has_and_belongs_to_many :categories

  has_many :photos, dependent: :destroy

  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  #validates :starts_at, presence: true#,date: { before:  :starts_at}
  #validates :ends_at, presence: true
  validate :end_date_after_start_date


  def end_date_after_start_date
    if ends_at.present? && starts_at.present? && ends_at <= starts_at
      errors.add :ends_at, "must be after start date"
    end
end

def bargain?
  price < 60
end

def self.order_by_price
    order :price
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
   where("first_name LIKE ?", "#{letter}%").order(:first_name)
 end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_secure_token

  has_many :registrations, dependent: :destroy

  has_many :booked_events, through: :registrations, source: :event
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end


end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    # render status: 200, json: {
    #   events: Event.all
    # }.to_json

    events =  Event.all
    render status: 200, json: events
  end

  def show
    event = Event.find(params[:id])
    render status: 200, json: events
    # render status: 200, json: {
    #   event: event
    # }.to_json
  end


  def create
    event1 = Event.new(event_params)

    if event1.save
      render status: 201, json: event1
      # render status: 201, json: {
      #   message: "event successfully created",
      #   event: event1
      # }.to_json
    else
      render status: 422, json: {
        errors: event.errors
      }.to_json
    end
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      render status: 200, json: event
      # render status: 200, json: {
      #   message: "Event successfully updated",
      #   event: event
      # }.to_json
    else
       render status: 422, json: {
        message: "The event could not be updated",
        errors: event.errors
      }.to_json
    end
  end

  def destroy
    event1 = Event.find(params[:id])
    event1.destroy
    render status: 200, json: {
      message: "Event successfully deleted"
    }.to_json
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks,
        :starts_at, :ends_at, :active)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      redirect_to edit_room_path(@event), notice: "Event created"
    end
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission"
    end
   end

  def update
    if @event.update(event_params)
      image_params.each do |image|
      @event.photos.create(image: image)
    end

    redirect_to edit_event_path(@event), notice: "Event updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
      .require(:event)
      .permit(
        :name, :description, :location, :price, :capacity, :includes_food,
        :includes_drinks, :starts_at, :ends_at, :active, theme_ids: []
      )
  end

  def image_params
    params[:images].present? ?
  params.require(:images) : []
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    @event = @photo.event

    @photo.destroy
    @photos = Photo.where(event_id: @event.id)

    # if @event.user.id == current_user.id
    #   photo.destroy
    #
    #   redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    # else
    #   redirect_to @event, notice: "Cannot delete that photo"

    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.js
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true} do |f| %>
<div class="form-group">
    <label>Event name</label>
    <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "location", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">

      <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
      <div class="input-group-addon">€</div>
    </div>
  </div>


  <div class="form-group">
      <label>Capacity</label>
      <%= f.select :capacity, options_for_select(10..100), placeholder: "capacity", class: "form-control" %>

    </div>

  <div class="form-group">
      <label>Start Date</label>
      <%= f.date_select :starts_at, class: "form-control" %>
    </div>

    <div class="form-group">
        <label>End Date</label>
        <%= f.date_select :ends_at, class: "form-control" %>
      </div>

      <label>Categories:</label>

<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>



   <label>Amenties</label>

  <div class="form-group">
    <%= f.check_box :includes_food %> Food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks
  </div>


  <label>Status</label>

    <div class="form-group">
      <%= f.check_box :active %> Active
    </div>

    <label>Photos</label>

<div class="form-group">
  <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
  <div id="photos">
  <%= render 'photos/list' %>
</div>

</div>


    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>

    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<!-- Registration Form -->
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Register in this Event</div>

    <div class="panel-body">
      <%= render 'registrations/form' %>
    </div>
  </div>
<% end %>



<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Event Name: <%= @event.name %></p>
    <p>Host Email: <%= @event.user.email %></p>
    <h3>Event Description: </h3>
    <p><h4><%= @event.description %></h4></p>
    <p>Location: <%= @event.location %></p>
    <p>Price: <%= @event.price %></p>
    <p>Capacity <%= @event.capacity %></p>
    <p>Starts at: <%= @event.starts_at %></p>
    <p>Ends at: <%= @event.ends_at %></p>
    <h3> Bonus Pleasure: </h3>
    <ul>
    <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
    <li><%= !@event.includes_drinks ? ("<s>Drinks</s>").html_safe : "Drinks" %></li>
  </ul>

  <!-- Categories -->
<h4>Categories:</h4>
<% @categories.each do |category| %>
  <span class="label label-primary"><%= category.name %></span>
<% end %>

<h4>Photos</h4>
<% @event.photos.each do |photo| %>
<div class="panel panel-default">
  <div class="panel-heading">
  <%= image_tag photo.image.thumbnail %>
<% end %>



  </div>
</div>


<%= link_to "Back", events_path, class: "btn btn-default" %>